# See CONTRIBUTING.rst, we expect this to be run via a git pre-commit hook.
# You can also run the checks directly at the terminal, e.g.
#
# $ pre-commit run --all-files
#
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-executables-have-shebangs
        files: \.(py|sh)$
    -   id: check-json
    -   id: end-of-file-fixer
        files: \.py$
    -   id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--check,--target-version,py37]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'flake8-rst-docstrings>=0.2.3',
            'pydocstyle>=6.0.0',
        ]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.6.0]
        exclude: ^.github/
-   repo: https://github.com/myint/rstcheck
    rev: v6.0.0.post1
    hooks:
    -   id: rstcheck
        args: [
            --ignore-roles=ref,
            --ignore-directives=toctree,
            --report-level=warning
        ]
-   repo: https://github.com/PyCQA/doc8
    rev: 0.11.2
    hooks:
    -   id: doc8
        additional_dependencies: [pygments]
        args: [--quiet,--ignore-path=Doc/examples/ec_*.txt, --ignore=D004]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        files: \.(rst|md|tex)$
        args: [
            --ignore-regex,
            '(^|\W)([A-Z]{2,3})(\W|$)',
            -L,
            'ser,hsa,hist,fpr'
        ]
-   repo: local
    hooks:
    -   id: doi-link-style
        name: Enforce https://doi.org/ style
        description: Check DOI link style, see https://www.crossref.org/display-guidelines/
        entry: '(?i)(doi:|dx\.doi\.org|http://doi\.org)'
        language: pygrep
        files: \.(rst|tex)$
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        name: vulnerability check
        # Limit check to the usage of assert in the code.
        # https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html
        args: [-t, "B101"]
        # Update the exclusion list when asserts are deleted from one of these files.
        # See: https://github.com/biopython/biopython/issues/3600
        exclude: |
            (?x)(
                ^Tests|
                ^Doc|
                ^Scripts/GenBank/check_output|
                ^Scripts/update_ncbi_codon_table|
                ^Scripts/xbbtools/nextorf|
                ^BioSQL/Loader|
                ^Bio/Align/__init__|
                ^Bio/Align/a2m|
                ^Bio/Align/bed|
                ^Bio/Align/clustal|
                ^Bio/Align/emboss|
                ^Bio/Align/exonerate|
                ^Bio/Align/hhr|
                ^Bio/Align/maf|
                ^Bio/Align/mauve|
                ^Bio/Align/nexus|
                ^Bio/Align/phylip|
                ^Bio/Align/psl|
                ^Bio/Align/sam|
                ^Bio/Align/stockholm|
                ^Bio/Align/substitution_matrices/__init__|
                ^Bio/Align/tabular|
                ^Bio/AlignIO/ClustalIO|
                ^Bio/AlignIO/EmbossIO|
                ^Bio/AlignIO/FastaIO|
                ^Bio/AlignIO/MafIO|
                ^Bio/AlignIO/MauveIO|
                ^Bio/AlignIO/MsfIO|
                ^Bio/AlignIO/NexusIO|
                ^Bio/AlignIO/PhylipIO|
                ^Bio/AlignIO/StockholmIO|
                ^Bio/Application/__init__|
                ^Bio/Blast/Applications|
                ^Bio/Blast/NCBIXML|
                ^Bio/Compass/__init__|
                ^Bio/Data/CodonTable|
                ^Bio/Emboss/Applications|
                ^Bio/Entrez/DTDs/NCBI_Variation\.mod\.dtd|
                ^Bio/Entrez/Parser|
                ^Bio/ExPASy/Enzyme|
                ^Bio/ExPASy/ScanProsite|
                ^Bio/File|
                ^Bio/GenBank/Scanner|
                ^Bio/GenBank/__init__|
                ^Bio/Geo/__init__|
                ^Bio/Graphics/BasicChromosome|
                ^Bio/Graphics/ColorSpiral|
                ^Bio/Graphics/GenomeDiagram/_AbstractDrawer|
                ^Bio/Graphics/GenomeDiagram/_CircularDrawer|
                ^Bio/Graphics/GenomeDiagram/_CrossLink|
                ^Bio/Graphics/GenomeDiagram/_LinearDrawer|
                ^Bio/HMM/MarkovModel|
                ^Bio/MarkovModel|
                ^Bio/MaxEntropy|
                ^Bio/Nexus/Trees|
                ^Bio/PDB/Atom|
                ^Bio/PDB/DSSP|
                ^Bio/PDB/FragmentMapper|
                ^Bio/PDB/HSExposure|
                ^Bio/PDB/NACCESS|
                ^Bio/PDB/NeighborSearch|
                ^Bio/PDB/PDBList|
                ^Bio/PDB/Residue|
                ^Bio/PDB/StructureAlignment|
                ^Bio/PDB/cealign|
                ^Bio/PDB/parse_pdb_header|
                ^Bio/PDB/qcprot|
                ^Bio/Phylo/BaseTree|
                ^Bio/Phylo/NewickIO|
                ^Bio/Phylo/PAML/_parse_codeml|
                ^Bio/Phylo/PhyloXML|
                ^Bio/Phylo/PhyloXMLIO|
                ^Bio/Restriction/Restriction|
                ^Bio/SCOP/__init__|
                ^Bio/SearchIO/BlastIO/blast_tab|
                ^Bio/SearchIO/BlastIO/blast_text|
                ^Bio/SearchIO/BlastIO/blast_xml|
                ^Bio/SearchIO/BlatIO|
                ^Bio/SearchIO/ExonerateIO/_base|
                ^Bio/SearchIO/ExonerateIO/exonerate_cigar|
                ^Bio/SearchIO/ExonerateIO/exonerate_text|
                ^Bio/SearchIO/ExonerateIO/exonerate_vulgar|
                ^Bio/SearchIO/FastaIO|
                ^Bio/SearchIO/HmmerIO/hmmer2_text|
                ^Bio/SearchIO/HmmerIO/hmmer3_domtab|
                ^Bio/SearchIO/HmmerIO/hmmer3_text|
                ^Bio/SearchIO/_legacy/NCBIStandalone|
                ^Bio/SearchIO/_model/hsp|
                ^Bio/SearchIO/_model/query|
                ^Bio/SearchIO/_utils|
                ^Bio/Seq|
                ^Bio/SeqFeature|
                ^Bio/SeqIO/AbiIO|
                ^Bio/SeqIO/AceIO|
                ^Bio/SeqIO/FastaIO|
                ^Bio/SeqIO/IgIO|
                ^Bio/SeqIO/InsdcIO|
                ^Bio/SeqIO/PhdIO|
                ^Bio/SeqIO/PirIO|
                ^Bio/SeqIO/QualityIO|
                ^Bio/SeqIO/SeqXmlIO|
                ^Bio/SeqIO/SffIO|
                ^Bio/SeqIO/TabIO|
                ^Bio/SeqIO/UniprotIO|
                ^Bio/SeqIO/__init__|
                ^Bio/SeqIO/_index|
                ^Bio/SeqRecord|
                ^Bio/SwissProt/__init__|
                ^Bio/TogoWS/__init__|
                ^Bio/Wise/__init__|
                ^Bio/Wise/psw|
                ^Bio/bgzf|
                ^Bio/codonalign/codonseq|
                ^Bio/motifs/alignace|
                ^Bio/motifs/minimal|
                ^Bio/pairwise2
            )
ci:
    # Settings for the https://pre-commit.ci/ continuous integration service
    autofix_prs: false
    # Default message is more verbose
    autoupdate_commit_msg: '[pre-commit.ci] autoupdate'
    # Default is weekly
    autoupdate_schedule: quarterly
    # Currently pre-commit.ci checks all files, and all hooks takes too long
    # and causes a timeout - so as a short-term workaround, skip flake8 etc:
    skip: [
        check-json,
        mixed-line-ending,
        flake8,
        rstcheck,
        doc8,
        codespell,
        doi-link-style
    ]
